export declare const assets: {
    logo: string;
    searchIcon: string;
    userIcon: string;
    calenderIcon: string;
    locationIcon: string;
    starIconFilled: string;
    arrowIcon: string;
    starIconOutlined: string;
    instagramIcon: string;
    facebookIcon: string;
    twitterIcon: string;
    linkendinIcon: string;
    freeWifiIcon: string;
    freeBreakfastIcon: string;
    roomServiceIcon: string;
    mountainIcon: string;
    poolIcon: string;
    closeIcon: string;
    homeIcon: string;
    locationFilledIcon: string;
    heartIcon: string;
    badgeIcon: string;
    menuIcon: string;
    closeMenu: string;
    guestsIcon: string;
    regImage: string;
    addIcon: string;
    dashboardIcon: string;
    listIcon: string;
    uploadArea: string;
    totalBookingIcon: string;
    totalRevenueIcon: string;
    hotelNotFound: string;
};
export declare const cities: string[];
export declare const exclusiveOffers: {
    _id: number;
    title: string;
    description: string;
    priceOff: number;
    expiryDate: string;
    image: string;
}[];
export declare const testimonials: {
    id: number;
    name: string;
    address: string;
    image: string;
    rating: number;
    review: string;
}[];
export declare const facilityIcons: {
    "Free WiFi": string;
    "Free Breakfast": string;
    "Room Service": string;
    "Mountain View": string;
    "Pool Access": string;
};
export declare const roomCommonData: {
    icon: string;
    title: string;
    description: string;
}[];
export declare const userDummyData: {
    _id: string;
    username: string;
    email: string;
    image: string;
    role: string;
    createdAt: string;
    updatedAt: string;
    __v: number;
    recentSearchedCities: string[];
};
export declare const hotelDummyData: {
    _id: string;
    name: string;
    address: string;
    contact: string;
    owner: {
        _id: string;
        username: string;
        email: string;
        image: string;
        role: string;
        createdAt: string;
        updatedAt: string;
        __v: number;
        recentSearchedCities: string[];
    };
    city: string;
    createdAt: string;
    updatedAt: string;
    __v: number;
};
export declare const roomsDummyData: {
    _id: string;
    hotel: {
        _id: string;
        name: string;
        address: string;
        contact: string;
        owner: {
            _id: string;
            username: string;
            email: string;
            image: string;
            role: string;
            createdAt: string;
            updatedAt: string;
            __v: number;
            recentSearchedCities: string[];
        };
        city: string;
        createdAt: string;
        updatedAt: string;
        __v: number;
    };
    roomType: string;
    pricePerNight: number;
    amenities: string[];
    images: string[];
    isAvailable: boolean;
    createdAt: string;
    updatedAt: string;
    __v: number;
}[];
export declare const userBookingsDummyData: {
    _id: string;
    user: {
        _id: string;
        username: string;
        email: string;
        image: string;
        role: string;
        createdAt: string;
        updatedAt: string;
        __v: number;
        recentSearchedCities: string[];
    };
    room: {
        _id: string;
        hotel: {
            _id: string;
            name: string;
            address: string;
            contact: string;
            owner: {
                _id: string;
                username: string;
                email: string;
                image: string;
                role: string;
                createdAt: string;
                updatedAt: string;
                __v: number;
                recentSearchedCities: string[];
            };
            city: string;
            createdAt: string;
            updatedAt: string;
            __v: number;
        };
        roomType: string;
        pricePerNight: number;
        amenities: string[];
        images: string[];
        isAvailable: boolean;
        createdAt: string;
        updatedAt: string;
        __v: number;
    } | undefined;
    hotel: {
        _id: string;
        name: string;
        address: string;
        contact: string;
        owner: {
            _id: string;
            username: string;
            email: string;
            image: string;
            role: string;
            createdAt: string;
            updatedAt: string;
            __v: number;
            recentSearchedCities: string[];
        };
        city: string;
        createdAt: string;
        updatedAt: string;
        __v: number;
    };
    checkInDate: string;
    checkOutDate: string;
    totalPrice: number;
    guests: number;
    status: string;
    paymentMethod: string;
    isPaid: boolean;
    createdAt: string;
    updatedAt: string;
    __v: number;
}[];
export declare const dashboardDummyData: {
    totalBookings: number;
    totalRevenue: number;
    bookings: {
        _id: string;
        user: {
            _id: string;
            username: string;
            email: string;
            image: string;
            role: string;
            createdAt: string;
            updatedAt: string;
            __v: number;
            recentSearchedCities: string[];
        };
        room: {
            _id: string;
            hotel: {
                _id: string;
                name: string;
                address: string;
                contact: string;
                owner: {
                    _id: string;
                    username: string;
                    email: string;
                    image: string;
                    role: string;
                    createdAt: string;
                    updatedAt: string;
                    __v: number;
                    recentSearchedCities: string[];
                };
                city: string;
                createdAt: string;
                updatedAt: string;
                __v: number;
            };
            roomType: string;
            pricePerNight: number;
            amenities: string[];
            images: string[];
            isAvailable: boolean;
            createdAt: string;
            updatedAt: string;
            __v: number;
        } | undefined;
        hotel: {
            _id: string;
            name: string;
            address: string;
            contact: string;
            owner: {
                _id: string;
                username: string;
                email: string;
                image: string;
                role: string;
                createdAt: string;
                updatedAt: string;
                __v: number;
                recentSearchedCities: string[];
            };
            city: string;
            createdAt: string;
            updatedAt: string;
            __v: number;
        };
        checkInDate: string;
        checkOutDate: string;
        totalPrice: number;
        guests: number;
        status: string;
        paymentMethod: string;
        isPaid: boolean;
        createdAt: string;
        updatedAt: string;
        __v: number;
    }[];
};
