name: Run Backend Tests

on:
    pull_request:
        branches: [ main , backend, frontend, develop, merged-backend-frontend, backend|merge-features]
    push:
        branches: [ main , backend, frontend, develop, merged-backend-frontend, backend|merge-features]

jobs:
  test-server:
    name: Test Backend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hotelproject
          POSTGRES_PASSWORD: hotelproject
          POSTGRES_DB: db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: apps/server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clean and install fresh dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install
        
      - name: Install backend dependencies
        run: npm ci

      - name: Wait for PostgresSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U hotelproject; do
            echo "Waiting for PostgresSQL..."
            sleep 2
          done
      - name: Generate Prisma Client
        run: npx prisma generate
      
      - name: Run Prisma Generate
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://hotelproject:hotelproject@localhost:5432/db_test

      - name: Run backend tests
        run: npm test
        env:
          # Server Configuration
          PORT: 3000
          NODE_ENV: test
          
          # Frontend URL (for CORS)
          FRONTEND_URL: http://localhost:5173
          
          # JWT Configuration
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          
          # Database URLs
          DATABASE_URL: postgresql://hotelproject:hotelproject@localhost:5432/db_test
          DATABASE_TEST_URL: postgresql://hotelproject:hotelproject@localhost:5432/db_test
          
          # SMTP Configuration
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          
          # Base URL for email verification
          BASE_URL: http://localhost:3000
          
          # Stripe Configuration
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}