name: Run Fullstack Tests

on:
    pull_request:
        branches: [ main , backend, frontend]
    push:
        branches: [ main , backend, frontend]

jobs:
  test-server:
    name: Test Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        run: npm ci

      - name: Run backend tests
        run: npm test
